- name: Disable SELinux
  selinux:
    state: disabled
  ignore_errors: true

- name: Install nginx Repo.
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ nginx_repo_yum }}"

- name: Install packages
  yum:
    name:
        - nginx
        - mysql-server
        - wget
        - vim
        - openssl
        - python3
        - python3-pip
    state: present

- name: Update pip packages
  pip:
    name:
        - setuptools
        - pip
    state: latest

- name: Reset module php
  shell: dnf module reset php -y

- name: Enable module php
  shell: dnf module enable php:7.4 -y

- name: Install pip packages
  pip:
    name:
        - pymysql

- name: Installing php
  yum:
    name:
        - php
        - php-fpm
        - php-gd 
        - php-pdo
        - php-mbstring
        - php-mysqlnd
        - php-bcmath
        - php-pecl-zip
        - php-json   
    state: present

- name: Make sure mysql service is running
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Make sure php-fpm service is running
  systemd:
    name: php-fpm
    state: started
    enabled: yes

- name: Template archive default.conf
  template:
     src: wordpress.conf.j2
     dest: /etc/nginx/conf.d/wordpress.conf

- name: Template archive nginx.conf
  template:
     src: nginx.conf.j2
     dest: /etc/nginx/nginx.conf

- name: Template php.ini 
  template:
     src: php.ini.j2
     dest: /etc/php.ini
  notify: restart php   

- name: Make sure nginx service is running
  systemd:
    name: nginx
    state: restarted